# -*- coding: utf-8 -*-
"""Projeto 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15uhEivwvj2vNw6VPAA6tN9nAe7LKNlm2
"""

## Sistema de Cadastro de Produtos (Mini Controle de Estoque)
categorias = ("Alimentos", "Limpeza", "Bebidas")
produtos = []
codigos_cadastrados = set()

def menu():
    print("\n===== SISTEMA DE CADASTRO DE PRODUTOS =====")
    print("1 - Cadastrar produto")
    print("2 - Listar produtos")
    print("3 - Buscar produto")
    print("4 - Atualizar produto")
    print("5 - Excluir produto")
    print("0 - Sair")
    return input("Escolha uma opção: ")

def cadastrar_produto():
    try:
        codigo = int(input("Código do produto: "))
        if codigo in codigos_cadastrados:
            print("Código já cadastrado!")
            return
        nome = input("Nome do produto: ").capitalize()
        preco = float(input("Preço: "))
        quantidade = int(input("Quantidade: "))
        print("Categorias disponíveis:", categorias)
        categoria = input("Escolha uma categoria: ").capitalize()

        if categoria not in categorias:
            print("Categoria inválida! Produto não cadastrado.")
            return

        produto = {
            "codigo": codigo,
            "nome": nome,
            "preco": preco,
            "quantidade": quantidade,
            "categoria": categoria
        }

        produtos.append(produto)
        codigos_cadastrados.add(codigo)
        print("Produto cadastrado com sucesso!")

    except ValueError:
        print("Entrada inválida. Tente novamente.")

def listar_produtos():
    if not produtos:
        print("Nenhum produto cadastrado.")
        return
    print("\n--- LISTA DE PRODUTOS ---")
    for p in produtos:
        print(f"Código: {p['codigo']} | Nome: {p['nome']} | Preço: R${p['preco']:.2f} | "
              f"Qtd: {p['quantidade']} | Categoria: {p['categoria']}")

def buscar_produto():
    codigo = int(input("Informe o código do produto: "))
    for p in produtos:
        if p["codigo"] == codigo:
            print(f"Produto encontrado: {p}")
            return
    print("Produto não encontrado.")

def atualizar_produto():
    codigo = int(input("Informe o código do produto que deseja atualizar: "))
    for p in produtos:
        if p["codigo"] == codigo:
            p["nome"] = input("Novo nome: ").capitalize()
            p["preco"] = float(input("Novo preço: "))
            p["quantidade"] = int(input("Nova quantidade: "))
            print(" Produto atualizado com sucesso!")
            return
    print("Produto não encontrado.")

def excluir_produto():
    codigo = int(input("Código do produto para excluir: "))
    for p in produtos:
        if p["codigo"] == codigo:
            produtos.remove(p)
            codigos_cadastrados.remove(codigo)
            print(" Produto excluído com sucesso!")
            return
    print("Produto não encontrado.")

while True:
    opcao = menu()
    if opcao == "1":
        cadastrar_produto()
    elif opcao == "2":
        listar_produtos()
    elif opcao == "3":
        buscar_produto()
    elif opcao == "4":
        atualizar_produto()
    elif opcao == "5":
        excluir_produto()
    elif opcao == "0":
        print("Saindo...")
        break
    else:
        print("Opção inválida!")