# -*- coding: utf-8 -*-
"""Projeto 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bue5NDv16vx_fMUOsBf3VlYyF4dnLoXU
"""

# Sistema de Controle de Alunos e Notas

alunos = {}
nomes_cadastrados = set()

def menu():
    print("\n===== SISTEMA DE CONTROLE DE ALUNOS =====")
    print("1 - Cadastrar aluno")
    print("2 - Registrar notas")
    print("3 - Listar alunos e médias")
    print("4 - Buscar aluno")
    print("5 - Mostrar aprovados e reprovados")
    print("6 - Relatórios")
    print("0 - Sair")
    return input("Escolha uma opção: ")

def cadastrar_aluno():
    matricula = input("Digite a matrícula do aluno: ")
    nome = input("Nome do aluno: ").capitalize()
    if nome in nomes_cadastrados:
        print("Aluno já cadastrado!")
        return
    alunos[matricula] = ()
    nomes_cadastrados.add(nome)
    print("Aluno cadastrado com sucesso!")

def registrar_notas():
    matricula = input("Digite a matrícula do aluno: ")
    if matricula not in alunos:
        print("Matrícula não encontrada.")
        return
    notas = []
    for i in range(1, 4):
        nota = float(input(f"Digite a nota {i}: "))
        notas.append(nota)
    alunos[matricula] = tuple(notas)
    print("Notas registradas!")

def listar_alunos():
    if not alunos:
        print("Nenhum aluno cadastrado.")
        return
    for matricula, notas in alunos.items():
        if notas:
            media = sum(notas) / len(notas)
            print(f"Matrícula: {matricula} | Notas: {notas} | Média: {media:.2f}")
        else:
            print(f"Matrícula: {matricula} | Notas: não registradas")

def buscar_aluno():
    matricula = input("Digite a matrícula: ")
    if matricula in alunos:
        notas = alunos[matricula]
        media = sum(notas) / len(notas) if notas else 0
        print(f"Aluno: {matricula} | Notas: {notas} | Média: {media:.2f}")
    else:
        print("Aluno não encontrado.")

def mostrar_aprovados_reprovados():
    for matricula, notas in alunos.items():
        if notas:
            media = sum(notas) / len(notas)
            status = "Aprovado" if media >= 7 else "Reprovado"
            print(f"{matricula} - Média: {media:.2f} - {status}")

def relatorios():
    print("\n--- RELATÓRIOS ---")
    print("1 - Alunos cadastrados")
    print("2 - Médias individuais")
    print("3 - Aprovados e Reprovados")
    opc = input("Escolha: ")

    if opc == "1":
        print("Alunos cadastrados:", list(alunos.keys()))
    elif opc == "2":
        listar_alunos()
    elif opc == "3":
        mostrar_aprovados_reprovados()
    else:
        print("Opção inválida!")

while True:
    opcao = menu()
    if opcao == "1":
        cadastrar_aluno()
    elif opcao == "2":
        registrar_notas()
    elif opcao == "3":
        listar_alunos()
    elif opcao == "4":
        buscar_aluno()
    elif opcao == "5":
        mostrar_aprovados_reprovados()
    elif opcao == "6":
        relatorios()
    elif opcao == "0":
        print("Saindo...")
        break
    else:
        print("Opção inválida!")